name: ppsspp-emulator
base: core24
version: '1.19.3'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: A PlayStation Portable emulator
description: |
  PPSSPP is a PSP emulator that can run games in full HD resolution. It can even upscale textures that would otherwise be too blurry as they were made for the small screen of the original PSP.
grade: stable
confinement: strict

apps:
  ppsspp-emulator:
    command: usr/games/bin/PPSSPPSDL
    desktop: usr/games/share/applications/PPSSPPSDL.desktop
    common-id: org.ppsspp.PPSSPP
    environment:
      SDL_VIDEO_X11_WMCLASS: org.ppsspp.PPSSPP
      SDL_VIDEO_WAYLAND_WMCLASS: org.ppsspp.PPSSPP
      QT_QPA_PLATFORMTHEME: kde    
    extensions: [kde-neon-6]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

plugs:
  shared-memory:
    private: true

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [amd64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  ppsspp:
    plugin: cmake
    source: https://github.com/hrydgard/ppsspp.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libfontconfig1-dev
      - libvulkan-dev
      - libglew-dev
      - libzstd-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/games
      - -DUSE_SYSTEM_FFMPEG=OFF
      - -DUSE_SYSTEM_LIBZIP=ON
      - -DUSE_SYSTEM_ZSTD=ON
      - -DUSE_WAYLAND_WSI=ON
      - -DUSING_QT_UI=OFF
      - -DBUILD_TESTING=OFF
      - -DOpenGL_GL_PREFERENCE=GLVND
    override-build: |
      craftctl default
      sed -i 's|Name=PPSSPPSDL|Name=PPSSPP [NyKyu]|' $CRAFT_PART_INSTALL/usr/games/share/applications/PPSSPPSDL.desktop
      sed -i 's|Exec=PPSSPPSDL|Exec=${SNAP}/usr/games/bin/PPSSPPSDL|' $CRAFT_PART_INSTALL/usr/games/share/applications/PPSSPPSDL.desktop
      sed -i 's|Icon=ppsspp|Icon=${SNAP}/usr/games/share/icons/hicolor/scalable/apps/ppsspp.svg|' $CRAFT_PART_INSTALL/usr/games/share/applications/PPSSPPSDL.desktop

  qarma:
    after: [ppsspp]
    plugin: nil
    build-packages: [qmake6]
    source: https://github.com/luebking/qarma.git
    source-tag: v1.0.0
    override-build: |
      qmake6 PREFIX=$CRAFT_PART_INSTALL/
      make
      make install

  dependencies:
    after: [qarma]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
    prime:
      - usr/lib/x86_64-linux-gnu/libSDL2*
      - usr/lib/x86_64-linux-gnu/libdecor-0*

layout:
  /usr/games/share/ppsspp:
    symlink: $SNAP/usr/games/share/ppsspp
