name: ppsspp-emulator
base: core24
version: '1.20.2'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: A PlayStation Portable emulator
description: |
  PPSSPP is a PSP emulator that can run games in full HD resolution.
  It can even upscale textures that would otherwise be too blurry as they were made for the small screen of the original PSP.
grade: stable
confinement: strict
icon: ppsspp.svg

apps:
  ppsspp-emulator:
    command: usr/bin/PPSSPPSDL
    desktop: usr/share/applications/PPSSPPSDL.desktop
    common-id: org.ppsspp.PPSSPP
    environment:
      SDL_VIDEO_X11_WMCLASS: org.ppsspp.PPSSPP
      SDL_VIDEO_WAYLAND_WMCLASS: org.ppsspp.PPSSPP
    extensions: [gnome]
    plugs:
      - unity7
      - audio-playback
      - network
      - network-bind
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

plugs:
  shared-memory:
    private: true

layout:
  /usr/share/ppsspp:
    symlink: $SNAP/usr/share/ppsspp

parts:
  ppsspp:
    plugin: cmake
    source: https://github.com/hrydgard/ppsspp.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libfontconfig1-dev
      - libvulkan-dev
      - libglew-dev
      - libzstd-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DUSE_SYSTEM_FFMPEG=OFF
      - -DUSE_SYSTEM_LIBZIP=ON
      - -DUSE_SYSTEM_ZSTD=ON
      - -DUSE_WAYLAND_WSI=ON
      - -DUSING_QT_UI=OFF
      - -DBUILD_TESTING=OFF
      - -DOpenGL_GL_PREFERENCE=GLVND
    override-build: |
      craftctl default
      sed -i 's|Name=PPSSPPSDL|Name=PPSSPP [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/PPSSPPSDL.desktop

  zenity:
    after: [ppsspp]
    plugin: nil
    stage-packages: [zenity]
    prime:
      - usr/bin/zenity

  dependencies:
    after: [zenity]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libsamplerate0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamplerate*
